version: '3'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env  # Aquí se especifica el archivo .env
    depends_on:
      - database
      - keycloak
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  database:
    image: postgres
    container_name: Container_TC1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: ["start-dev"] 
    depends_on:
      - database
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

volumes:
  keycloak_data:
  postgres_data:
