version: '3'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=DB_TC1
    depends_on:
      - database
      - keycloak

  database:
    image: postgres
    container_name: Container_TC1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: DB_TC1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: DB_TC1
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: ["start-dev"] 
    depends_on:
      - database
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

volumes:
  keycloak_data:
  postgres_data:
