version: '3'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=DB_TC1
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: DB_TC1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
